#!/usr/bin/env bash
# build-docker.yml - OCI labels and manifest list annotations
#
# The standard set is generated by docker/metadata-action and can be switched
# off with IMAGE_METADATA; IMAGE_LABELS/IMAGE_ANNOTATIONS are the caller's own
# keys and apply either way, last, so a caller can override a standard value
# without giving up the rest of the set.
#
# Labels and annotations are the same values at two levels - image config and
# manifest list - so both come off a single metadata-action run in the 'infos'
# job. Only the labels can be applied there: annotations are attached later, at
# 'imagetools create' time in the merge job, once there is a manifest list to
# attach them to.

# shellcheck source=ci/tests/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

WORKFLOW="$WORKFLOWS_DIR/build-docker.yml"
META_STEP="Docker meta (labels and annotations)"

BLOCK=$(extract_run build-docker.yml merge "Create manifest list and push")

# The build step's labels are wired declaratively, so they are read from the
# YAML rather than executed: what matters is which values are listed and in
# which order, since the last '--label' for a key is the one that survives.
BUILD_LABELS=$(yq '
  .jobs.build.steps[]
  | select(.name == "Build docker image")
  | .with.labels
' "$WORKFLOW")

manifest_env() {
  export NORMALIZED_IMAGE="ghcr.io/acme/app"
  export DOCKER_METADATA_OUTPUT_JSON='{"tags":["ghcr.io/acme/app:1.2.3"]}'
  export DOCKER_ANNOTATIONS=$'index:org.opencontainers.image.revision=abc123\nindex:org.opencontainers.image.version=1.2.3'
  export IMAGE_ANNOTATIONS=""
}

# One digest file per architecture, named the way the 'Export digest' step
# writes them (the sha256 hex, no 'sha256:' prefix) - the block turns each
# into a '<image>@sha256:<digest>' reference. Mirrors working-directory:
# by cd-ing the test itself into the fixture digests dir.
write_digest_files() {
  mkdir -p "$SANDBOX/digests"
  cd "$SANDBOX/digests" || exit 1
  touch "$@"
}

# The format string is the caller's so a failure can print a value with %q,
# where the exact bytes are the point.
# shellcheck disable=SC2059
fail() {
  printf "FAIL: $1\n" "${@:2}" >&2
  exit 1
}

test_passes_each_standard_annotation_as_its_own_flag() {
  manifest_env
  write_digest_files "deadbeef"

  run_block "$BLOCK"

  assert_status 0
  assert_called 'docker|buildx imagetools create -t ghcr.io/acme/app:1.2.3 --annotation index:org.opencontainers.image.revision=abc123 --annotation index:org.opencontainers.image.version=1.2.3 ghcr.io/acme/app@sha256:deadbeef'
}

test_omits_annotation_flags_when_there_is_nothing_to_annotate() {
  manifest_env
  export DOCKER_ANNOTATIONS=""
  write_digest_files "deadbeef"

  run_block "$BLOCK"

  assert_status 0
  assert_not_called "--annotation"
  # Nothing to annotate must not cost the push itself - an empty source has to
  # leave the loop's exit status alone under the runner's `bash -e`.
  assert_called 'docker|buildx imagetools create -t ghcr.io/acme/app:1.2.3 ghcr.io/acme/app@sha256:deadbeef'
}

test_custom_annotations_apply_when_the_standard_set_is_off() {
  manifest_env
  # What the merge job sees when IMAGE_METADATA is false: the step producing
  # the standard set is skipped, so its output is empty.
  export DOCKER_ANNOTATIONS=""
  export IMAGE_ANNOTATIONS="com.example.team=platform"
  write_digest_files "deadbeef"

  run_block "$BLOCK"

  assert_status 0
  # Levelled here rather than by metadata-action, since the standard set it
  # would have levelled is switched off.
  assert_called "--annotation index:com.example.team=platform"
  assert_not_called "org.opencontainers.image.revision"
}

test_custom_annotations_come_after_the_standard_ones() {
  manifest_env
  export IMAGE_ANNOTATIONS=$'com.example.team=platform\norg.opencontainers.image.version=9.9.9'
  write_digest_files "deadbeef"

  run_block "$BLOCK"

  assert_status 0
  # Last '--annotation' for a key wins, so the caller's version must follow
  # the standard one rather than precede it.
  assert_called "--annotation index:org.opencontainers.image.version=1.2.3 --annotation index:com.example.team=platform --annotation index:org.opencontainers.image.version=9.9.9"
}

test_custom_annotations_are_trimmed_and_blank_lines_dropped() {
  manifest_env
  export DOCKER_ANNOTATIONS=""
  # A YAML block scalar strips only the common indentation, so a caller can
  # hand over lines that are still indented, and a trailing blank one.
  export IMAGE_ANNOTATIONS=$'  com.example.team=platform  \n\n\tcom.example.cost-center=1234\n'
  write_digest_files "deadbeef"

  run_block "$BLOCK"

  assert_status 0
  assert_called "--annotation index:com.example.team=platform --annotation index:com.example.cost-center=1234"
  # A level prefix glued onto leading whitespace would annotate a key that
  # starts with spaces; a blank line would annotate nothing at all.
  assert_not_called "index: "
  assert_not_called "--annotation index: "
}

test_build_step_applies_custom_labels_after_the_standard_ones() {
  local last
  last=$(printf '%s\n' "$BUILD_LABELS" | grep -v '^[[:space:]]*$' | tail -1)

  if [[ "$BUILD_LABELS" != *"docker-labels"* ]]; then
    fail 'build step labels do not carry the standard set from the infos job\n%s' "$BUILD_LABELS"
  fi

  if [[ "$last" != *'inputs.IMAGE_LABELS'* ]]; then
    fail 'IMAGE_LABELS is not the last labels entry, so it cannot override a standard key (got %q)' "$last"
  fi
}

# The gate lives in the step's `if:`, so switching IMAGE_METADATA off empties
# both outputs at the source rather than being re-tested in the merge script.
test_standard_set_is_gated_on_image_metadata() {
  local gate source
  gate=$(yq ".jobs.infos.steps[] | select(.name == \"$META_STEP\") | .if" "$WORKFLOW")
  [[ "$gate" == *"inputs.IMAGE_METADATA"* ]] \
    || fail 'the standard set is not gated on IMAGE_METADATA (got %q)' "$gate"

  source=$(yq '
    .jobs.merge.steps[]
    | select(.name == "Create manifest list and push")
    | .env.DOCKER_ANNOTATIONS
  ' "$WORKFLOW")
  [[ "$source" == *"needs.infos.outputs.docker-annotations"* ]] \
    || fail 'the merge job does not read the gated annotations output (got %q)' "$source"
}

# Labels and annotations are the same values, so they have to be one
# metadata-action run: a second one takes its own clock reading for
# org.opencontainers.image.created, and the index ends up disagreeing with the
# images underneath it about when they were built.
test_labels_and_annotations_come_from_one_metadata_run() {
  local producers levels
  producers=$(yq '[.jobs.*.steps[] | select(.with.annotations) | .name] | join(", ")' "$WORKFLOW")
  [ "$producers" = "$META_STEP" ] \
    || fail 'the standard annotations must come from the one run that also produces the labels (producers: %s)' "$producers"

  [ "$(yq ".jobs.infos.steps[] | select(.name == \"$META_STEP\") | .with | has(\"labels\")" "$WORKFLOW")" = "true" ] \
    || fail 'that run no longer produces the labels, so the two sets are back on separate clocks'

  # imagetools create rejects manifest-level annotations, so the level the run
  # emits is load-bearing, not cosmetic.
  levels=$(yq ".jobs.infos.steps[] | select(.name == \"$META_STEP\") | .env.DOCKER_METADATA_ANNOTATIONS_LEVELS" "$WORKFLOW")
  [ "$levels" = "index" ] \
    || fail 'annotations must be emitted at index level for imagetools create (got %q)' "$levels"
}

run_tests
